export const siteConfig = {
  name: "ilovecactusch",
  brand: "ilovecactus",
  title:
    "Comprar Suculentas y Cactus Online Chile | Envío Nacional | ilovecactusch",
  description:
    "Compra suculentas y cactus online en Chile. Tienda en Rancagua con catálogo, precios y envío a todo el país. Plantas únicas para hogar, oficina y regalo.",
  tagline: "El arte de decorar con vida",
  url: "https://ilovecactusch.cl",
  locale: "es_CL",
  language: "es",
  instagram: "https://www.instagram.com/ilovecactusch/",
  ogImage: "/products/product-2.png",
  keywords: [
    "comprar suculentas",
    "comprar suculentas chile",
    "comprar suculentas online",
    "comprar cactus",
    "comprar cactus chile",
    "comprar cactus online",
    "venta de suculentas",
    "venta de cactus",
    "tienda de suculentas",
    "tienda de cactus",
    "suculentas chile",
    "cactus chile",
    "suculentas rancagua",
    "cactus rancagua",
    "envío suculentas chile",
    "envío cactus chile",
    "plantas suculentas precio",
    "cactus y suculentas",
    "suculentas para regalo",
    "plantas de interior chile",
    "cactus san pedro chile",
    "ilovecactusch",
  ],
  location: {
    city: "Rancagua",
    region: "O'Higgins",
    country: "Chile",
    countryCode: "CL",
  },
};
